import type { Receipt } from "../analyze/receipt.js";
import { CAUSE_TEXT, tok, usd } from "./terminal.js";

const esc = (s: unknown): string => String(s).replace(/[&<>"']/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[ch]!);
const when = (ms: number): string => new Date(ms).toISOString().replace("T", " ").slice(0, 16) + " UTC";

/** Self-contained HTML receipt. No external resources; readable in light and dark. */
export function renderReceiptHtml(r: Receipt): string {
  const max = Math.max(...r.items.map((i) => i.cost.total), 1e-9);
  const rows = r.items
    .map((it) => {
      const u = it.turn.usage;
      const causes = it.findings.filter((f) => f.attributed > 0).map((f) => `<span class="tag" title="${esc(JSON.stringify(f.evidence))}">${esc(f.cause)} ${esc(usd(f.attributed))}</span>`).join(" ");
      const gap = it.gapMs === null ? "" : it.gapMs > 3_600_000 ? `${Math.round(it.gapMs / 3_600_000)}h` : `${Math.round(it.gapMs / 60_000)}m`;
      return `<tr>
<td class="n">${it.index + 1}</td><td>${esc(when(it.turn.ts))}</td><td class="n">${esc(gap)}</td><td>${esc(it.turn.model.replace("claude-", ""))}${it.turn.agentId ? ' <span class="tag">subagent</span>' : ""}</td>
<td class="n">${esc(tok(u.input_tokens))}</td><td class="n">${esc(tok(u.cache_creation?.ephemeral_5m_input_tokens ?? 0))}</td><td class="n">${esc(tok(u.cache_creation?.ephemeral_1h_input_tokens ?? 0))}</td><td class="n">${esc(tok(u.cache_read_input_tokens))}</td><td class="n">${esc(tok(u.output_tokens))}</td>
<td class="n cost"><div class="bar" style="width:${((it.cost.total / max) * 100).toFixed(1)}%"></div>${esc(usd(it.cost.total))}</td><td>${causes}</td></tr>`;
    })
    .join("\n");
  const causeRows = r.byCause.map((b) => `<tr><td>${esc(b.cause)}</td><td class="n">${b.turns}</td><td class="n">${esc(usd(b.attributed))}</td><td>${esc(CAUSE_TEXT[b.cause] ?? "")}</td></tr>`).join("\n");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>billproof receipt ${esc(r.sessionId.slice(0, 8))}</title>
<style>
:root{--bg:#fbfaf7;--fg:#1c1b18;--dim:#6b6860;--line:#e6e2d8;--bar:#d9c8a3;--tag:#efe9dc;color-scheme:light dark}
@media(prefers-color-scheme:dark){:root{--bg:#161512;--fg:#ece8de;--dim:#9a958a;--line:#2b2924;--bar:#4a4030;--tag:#26241f}}
body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.45 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;padding:32px}
h1{font-size:18px;margin:0 0 4px;font-weight:600}.sub{color:var(--dim);margin-bottom:24px}
.total{font-size:32px;font-weight:600;margin:12px 0 28px}
h2{font-size:13px;letter-spacing:.06em;text-transform:uppercase;color:var(--dim);margin:28px 0 8px;font-weight:600}
table{border-collapse:collapse;width:100%}th,td{text-align:left;padding:6px 10px;border-bottom:1px solid var(--line);vertical-align:top}
th{color:var(--dim);font-weight:500}td.n,th.n{text-align:right;white-space:nowrap}
.cost{position:relative}.bar{position:absolute;left:0;top:4px;bottom:4px;background:var(--bar);z-index:0;opacity:.6}.cost{isolation:isolate}.cost > *{position:relative}
.tag{display:inline-block;background:var(--tag);border-radius:3px;padding:1px 6px;font-size:12px;margin:1px 2px 1px 0;white-space:nowrap}
.foot{color:var(--dim);margin-top:28px;font-size:12px}
.wrap{overflow-x:auto}
</style></head><body>
<h1>billproof receipt</h1>
<div class="sub">session ${esc(r.sessionId)} · ${esc(r.project)} · ${esc(when(r.from))} to ${esc(when(r.to))} · ${r.turns} billed requests</div>
<div class="total">${esc(usd(r.total))}</div>
<h2>Where the money went</h2>
<div class="wrap"><table><thead><tr><th>cause</th><th class="n">turns</th><th class="n">attributed</th><th>meaning</th></tr></thead><tbody>${causeRows}</tbody></table></div>
<h2>Every turn</h2>
<div class="wrap"><table><thead><tr><th class="n">#</th><th>time</th><th class="n">gap</th><th>model</th><th class="n">in</th><th class="n">w5m</th><th class="n">w1h</th><th class="n">read</th><th class="n">out</th><th class="n">cost</th><th>causes</th></tr></thead><tbody>${rows}</tbody></table></div>
<div class="foot">Prices from platform.claude.com/docs/en/about-claude/pricing as of 2026-09-02. Attributions explain a turn's cost from several angles and are not meant to sum to the total. Hover a cause for the evidence that fired it. Generated by billproof; nothing in this file left your machine.</div>
</body></html>`;
}
